### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by raytung** [asbiin/semantic-release-github-pullrequest#86]
**Describe the solution you'd like**
Heya, we were using this project in tandem with https://github.com/pmowrer/semantic-release-monorepo to support our monorepo workflow. We did find, however, that this project does not support monorepos and the `assets` are assumed to be at the relative to the repo root (rather than subprojects).

This is a simplified version of our repo setup
```
.
├── subproject A
│   ├── .releaserc.js
│   └── package.json
├── subproject B

```

And our `.releaserc.js` looks like this
```
module.exports = {
  extends: 'semantic-release-monorepo',
  branches: ['main'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/npm',
    ['@semantic-release/github', { failComment: false, failTitle: false }],
    ['semantic-release-github-pullrequest', { assets: ['package.json'] }],
  ],
  preset: 'conventionalcommits',
};
```

When we run `semantic-release` inside subproject A, the package was successfully published, and a PR has been raised with the updated `package.json`. However, the `package.json` was added to the repository root rather than under subproject A

**Comment by asbiin** [comment]
implemented in #87
